### ISSUE TITLE
HexGrid sometimes cuts off patterns

### ISSUE THREAD

**Issue by object-Object** [JohnDog3112/Hex-Renderer#1]
While working on integrating the [Python FFI](https://github.com/JohnDog3112/hex_renderer_python) into [HexBug](https://github.com/object-Object/HexBug), I found some cases where one pattern is rendered partially or entirely outside of the grid. I initially noticed this with a long list of patterns, but I was able to reproduce it with a simpler example as well. It seems to only occur with specific combinations of `patterns` and `max_width` - adding/removing patterns, changing the shape of any patterns, or changing `max_width` will make all of the patterns visible again.

## Setup

I used the following function to render all of the examples:

```py
from pathlib import Path

from hex_renderer_py import (
    CollisionOption,
    Color,
    GridOptions,
    GridPatternOptions,
    HexGrid,
    Intersections,
    Lines,
    Marker,
    PatternVariant,
    Point,
    Triangle,
)


def draw(patterns: list[PatternVariant], max_width: int, filename: str = "out.png"):
    grid = HexGrid(list(patterns), max_width=max_width)
    options = GridOptions(
        line_thickness=0.12,
        pattern_options=GridPatternOptions.Uniform(
            intersections=Intersections.UniformPoints(
                point=Point.Single(
                    marker=Marker(
                        color=Color(255, 255, 255, 255),
                        radius=0.16,
                    )
                ),
            ),
            lines=Lines.SegmentColors(
                colors=[Color(255, 255, 255, 255)],
                triangles=Triangle.None_(),
                collisions=CollisionOption.ParallelLines(),
            ),
        ),
        center_dot=Point.None_(),
    )
    scale = grid.get_bound_scale((512, 512), options)
    data = bytes(grid.draw_png(scale, options))
    with open(Path(__file__).parent / filename, "wb") as f:
        f.write(data)
```

## Examples

In most of these examples, the only difference is the signature of the first pattern in the list.

1. All patterns are visible, but the points on the right and bottom edges are slightly cut off:

![out](https://github.com/user-attachments/assets/80d916f4-9535-4be2-9b83-91b261e9617b)

```py
draw(
    patterns=[
        PatternVariant("EAST", "wqq"),
        PatternVariant("EAST", "a"),
        PatternVariant("NORTH_WEST", "a"),
        PatternVariant("SOUTH_WEST", "a"),
    ],
    max_width=6,
)
```

2. The fourth pattern is completely outside of the visible area:

![out](https://github.com/user-attachments/assets/d65ad3d8-f073-4c62-a92e-beed93ba28d2)

```py
draw(
    patterns=[
        PatternVariant("EAST", "wwqq"),
        PatternVariant("EAST", "a"),
        PatternVariant("NORTH_WEST", "a"),
        PatternVariant("SOUTH_WEST", "a"),
    ],
    max_width=6,
)
```

3. Only half of the fourth pattern is visible:

![out](https://github.com/user-attachments/assets/bf7fbc74-a796-4560-9486-74d3f10d1d9a)

```py
draw(
    patterns=[
        PatternVariant("EAST", "wwwqq"),
        PatternVariant("EAST", "a"),
        PatternVariant("NORTH_WEST", "a"),
        PatternVariant("SOUTH_WEST", "a"),
    ],
    max_width=6,
)
```

4. Same as example 2, but `max_width` is different, so all patterns are visible again:

![out](https://github.com/user-attachments/assets/311fa9af-dccd-4507-86b9-fbcd414571e1)

```py
draw(
    patterns=[
        PatternVariant("EAST", "wwqq"),
        PatternVariant("EAST", "a"),
        PatternVariant("NORTH_WEST", "a"),
        PatternVariant("SOUTH_WEST", "a"),
    ],
    max_width=7,
)
```

**Comment by JohnDog3112** [comment]
So, I have a check that tries to find the right most point so it can properly crop the image. However, this check was only done for the first pattern and when adding a pattern causes a new row to be added. So, when the last pattern given is also the right most pattern, no check is done so it uses the previous rows left most points. Adding a condition to check it for the last pattern seems to have fixed it for the cases you gave above.

As for padding, I'm not completely sure why it's doing that? I fixed it by just multiplying my previous padding calculations by 1.1 and that seems to have fixed it, so I'll leave it for now.

The fixed version is already published for Rust, I will be working on the Python bindings in a little bit.

![image](https://github.com/user-attachments/assets/064c1ac6-1c32-4694-adc2-9d3a5db436be)
