### ISSUE TITLE
`CollisionOption.OverloadedParallel` draws both a parallel line and the overload when the number of lines is exactly `max_line`

### ISSUE THREAD

**Issue by object-Object** [JohnDog3112/Hex-Renderer#2]
Example with the pattern `EAST aaaaaa`:

![image](https://github.com/user-attachments/assets/8485c98e-1de4-4cb8-889d-bd33e2bd572c)

```py
collisions=CollisionOption.OverloadedParallel(
    max_line=3,
    overload=OverloadOptions.Dashes(
        color=palette.collision_color,
    ),
),
```

**Comment by JohnDog3112** [comment]
Apparently I checked the number of times the renderer has visited that line so far, not how many times it *will* visit it. It's fixed now and was fixed in the last (0.2.5 Hex_Renderer or 0.1.3 hex_renderer_py).
